"""Screening model, not measured hand performance. Python standard library only."""
import json, math
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
K=0.0980665
stall_kgcm=21.0 # DS3225 manufacturer at 5 V; owned generic unit is unidentified.
working_fraction=0.40 # Assumption, NOT a continuous-duty rating.
margin=1.5
radius_mm=12+0.6/2 # Single layer: groove floor plus half tendon diameter.
tau=stall_kgcm*K*working_fraction
r=radius_mm/1000
limit=tau/(margin*r)
rows=[]
for eta in [0.4,0.6,0.8]:
    tension=eta*limit/2
    rows.append(dict(routing_efficiency=eta,pair_tendon_N_each=tension,thumb_tendon_N=eta*limit,
        illustrative_tip_N_each=max(0,tension-4)*5/50))
loads=[]
for each in [5,10,15,20]:
    required=margin*r*2*each/.6
    loads.append(dict(required_finger_side_tendon_N_each=each,design_torque_Nm=required,
        design_torque_kgcm=required/K,within_assumed_working_allowance=required<=tau))
travel=[dict(sweep_deg=a,take_up_mm=radius_mm*math.radians(a)) for a in [18,120,160,180]]
result=dict(reference='DS3225 at 5 V, https://dsservo.com/d_file/DS3225%20datasheet.pdf',
    assumptions=dict(stall_kgcm=stall_kgcm,working_fraction=working_fraction,load_margin=margin,
      effective_radius_mm=radius_mm,tip_example_return_equivalent_N=4,tip_example_moment_arm_mm=5,
      tip_example_contact_lever_mm=50,equaliser='ideal equal arms and parallel output lines'),
    working_torque_Nm=tau,servo_side_total_tension_screen_N=limit,sensitivity=rows,loads=loads,travel=travel,
    limitations=['Friction, return tension and finger lever arms are assumed, not measured.',
      'Equaliser travel and routing are unfinished; no grip or structural acceptance.',
      'Measure full-path input force without applying routing loss twice.',
      'No current limiting or force feedback is inferred from this calculation.'])
(ROOT/'calculations/tendon_forces.json').write_text(json.dumps(result,indent=2)+'\n')
lines=['# Current spool: force and travel calculation','',
'Generated by `python3 calculations/tendon_forces.py`. These are screening calculations, not a measurement of the Phoenix hand.', '',
'![Force and travel trade-off](force_travel.png)', '', 'Optional plot: run `python calculations/plot_forces.py` with matplotlib installed.', '', '## Inputs and equations','',
f'Reference stall torque at 5 V: {stall_kgcm:g} kgf·cm. Assumed working fraction: 40%; torque allowance: {tau:.3f} N·m. Apply a separate 1.5 load margin. Neither allowance is a manufacturer continuous rating.', '',
'The new 6.75 mm-high single-groove spool retains its 12 mm groove-floor radius. With 0.6 mm line the effective radius is 12.3 mm. One line pulls a floating equaliser for each pair; one line pulls the thumb. Equal-arm, parallel-line geometry is assumed.', '',
'`required torque = margin × radius × (T1 + T2) / routing efficiency`',
'`equal finger tension limit = efficiency × working torque / (2 × margin × radius)`',
'`take-up = radius × angular travel in radians`','',
'## Available finger-side tendon tension','',
'| Routing efficiency | Paired fingers, each (N) | Single thumb (N) | Illustrative fingertip force per paired finger (N) |',
'| --- | ---: | ---: | ---: |']
for x in rows:lines.append(f"| {x['routing_efficiency']:.0%} | {x['pair_tendon_N_each']:.2f} | {x['thumb_tendon_N']:.2f} | {x['illustrative_tip_N_each']:.2f} |")
lines += ['', 'The fingertip column uses `(tendon tension − 4 N) × 5 mm / 50 mm`: an assumed equivalent return/friction tension, tendon moment arm and contact lever. These are not dimensions extracted from Phoenix CAD. A multi-joint finger needs pose-dependent tendon moment arms and contact geometry. Tendon tension is not grip force. The thumb column is tendon tension only.', '',
'## Torque required by an assumed load, 60% routing efficiency','',
'| Finger-side tendon pull per finger (N) | Design torque (N·m) | Design torque (kgf·cm) | Within assumed allowance? |',
'| --- | ---: | ---: | --- |']
for x in loads:lines.append(f"| {x['required_finger_side_tendon_N_each']} | {x['design_torque_Nm']:.3f} | {x['design_torque_kgcm']:.2f} | {'Yes' if x['within_assumed_working_allowance'] else 'No'} |")
lines += ['', 'Required pulls include return bands, finger-joint friction and desired contact load, but exclude routing friction already represented by efficiency. For unequal loads use their sum; a jammed finger can invalidate the equal-load assumption.', '',
'## Travel','', '| Usable sweep | Ideal line take-up |', '| --- | ---: |']
for x in travel:lines.append(f"| {x['sweep_deg']}° | {x['take_up_mm']:.2f} mm |")
lines += ['', '160° is an illustrative calibrated range, not the firmware command. The small initial firmware sweep is about 18° on the reference servo. For an ideal equaliser, input travel is the average of output travels; its tilt and mechanical stops must accommodate their difference. A 20/30 mm finger-travel pair needs 25 mm centre travel and 10 mm differential travel. An equaliser hitting a stop no longer shares force as assumed.', '',
f'If measuring with a force gauge at the servo end through the complete routing, the total input-force screening limit is **{limit:.2f} N**. Compare `1.5 × measured input force × 0.0123 m` against {tau:.3f} N·m; do not divide by routing efficiency again.', '',
'## What the numbers establish','',
'At 60% routing efficiency the model supports about 13.4 N per paired finger. Two fingers requiring 10 N each are within the assumed allowance; two requiring 15 N each are outside it. Actual required closure force is unknown. Measure maximum force and travel with return bands installed, first unloaded and then on a bench contact fixture. Record breakaway peaks and the highest winding radius. Do not tighten live tendons on a wearer to establish these values.', '',
'Reducing spool height preserves the force/travel calculation; reducing radius would raise force but reduce travel. The new spool still requires real horn, screw-head, tendon-anchor and printed-strength checks. These force estimates do not validate the motor restraints, wrist cradle or socket.', '',
'[Manufacturer reference datasheet](https://dsservo.com/d_file/DS3225%20datasheet.pdf), checked 5 October 2026. The owned generic servo is not identified by this reference.']
(ROOT/'calculations/README.md').write_text('\n'.join(lines)+'\n')
print(json.dumps(result,indent=2))
